b=document.getElementById("dark")
b.addEventListener("click",function()
{
    document.querySelector("body").classList.add("dark-back")
    // b.style.color="white"
    for(var i=0;i<62;i++){
        document.getElementsByClassName("module")[i].style.boxShadow="none";
        }
    document.getElementById("light").style.color="white"

})
document.getElementById("light").addEventListener("click",function()
{
    document.querySelector("body").classList.remove("dark-back")
    for(var i=0;i<62;i++){
        document.getElementsByClassName("module")[i].removeAttribute("style");
        }
})

document.getElementsByClassName("mech-mod-1-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-1-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})


// module 2 mechsics-----------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-2-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-2.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-15")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-16")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-17")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-2-18")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})


// mechsics module 3 -----------------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-3-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})

document.getElementsByClassName("mech-mod-3-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-11.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-3-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})

// mechsics module 4-------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-4-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-4.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-5.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-5.1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-5.2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-4-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})


// module 5 mechsics---------------------------------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-5-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-10.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})


