b=document.getElementById("dark")
b.addEventListener("click",function()
{
    document.querySelector("body").classList.add("dark-back")
    // b.style.color="white"
    for(var i=0;i<62;i++){
        document.getElementsByClassName("module")[i].style.boxShadow="none";
        }
    document.getElementById("light").style.color="white"

})
document.getElementById("light").addEventListener("click",function()
{
    document.querySelector("body").classList.remove("dark-back")
    for(var i=0;i<62;i++){
        document.getElementsByClassName("module")[i].removeAttribute("style");
        }
})

document.getElementsByClassName("mech-mod-1-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/aQf6Q8t1FQE")
})
document.getElementsByClassName("mech-mod-1-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/26pvB8YpTIE")
})
document.getElementsByClassName("mech-mod-1-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/KTmnGZ_MX1c")
})
document.getElementsByClassName("mech-mod-1-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/Xi7vChMhlAI")
})
document.getElementsByClassName("mech-mod-1-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/i-9wuvYzom4")
})
document.getElementsByClassName("mech-mod-1-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/g2FFbB2rJX4")
})
document.getElementsByClassName("mech-mod-1-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/ucswaIKmAnQ")
})
document.getElementsByClassName("mech-mod-1-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/7OXQNv73qr4")
})
document.getElementsByClassName("mech-mod-1-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/CK40-e2qu7I")
})
document.getElementsByClassName("mech-mod-1-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/hVFjJJLJizA")
})
document.getElementsByClassName("mech-mod-1-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/DRM1n5I-jkY")
})
document.getElementsByClassName("mech-mod-1-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/yFsD6XjJ1bU")
})
document.getElementsByClassName("mech-mod-1-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/aUru8WUUUGo")
})
document.getElementsByClassName("mech-mod-1-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/FOS9xFNUQUA")
})
document.getElementsByClassName("mech-mod-1-15")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/5Y29tsPFEMo")
})
document.getElementsByClassName("mech-mod-1-16")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/0sQOKC8GJYg")
})
document.getElementsByClassName("mech-mod-1-17")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/HEnKLtdmx1Q")
})


// module 2 mechsics-----------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-2-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/aaopC0Dftbo")
})
document.getElementsByClassName("mech-mod-2-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/V60oxexIH14")
})
document.getElementsByClassName("mech-mod-2-2.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/TvxaKdQ8BRk")
})
document.getElementsByClassName("mech-mod-2-2.1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/uQnu2pdv6oc")
})
document.getElementsByClassName("mech-mod-2-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/Kk8B-jLx_8M")
})
document.getElementsByClassName("mech-mod-2-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/ukDnJBnqv-k")
})
document.getElementsByClassName("mech-mod-2-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/GpGR3-wQjzI")
})
document.getElementsByClassName("mech-mod-2-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/TxOgIOuFDYA")
})
document.getElementsByClassName("mech-mod-2-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/gVep0zwue1U")
})
document.getElementsByClassName("mech-mod-2-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/qj-4qm45Hes")
})
document.getElementsByClassName("mech-mod-2-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/uOlpzAqO7AM")
})
document.getElementsByClassName("mech-mod-2-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/PjcdqAkP0UA")
})
document.getElementsByClassName("mech-mod-2-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/l3MSL1ZcJcg")
})
document.getElementsByClassName("mech-mod-2-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/4skt_FJVgpQ")
})
document.getElementsByClassName("mech-mod-2-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/bpNS7X_-hHE")
})
document.getElementsByClassName("mech-mod-2-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/KKMwkamUKj4")
})
document.getElementsByClassName("mech-mod-2-15")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/2XEPgx13tAY")
})
document.getElementsByClassName("mech-mod-2-16")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/kaVoLEBebjA")
})
document.getElementsByClassName("mech-mod-2-17")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/SYQnDUvenjs")
})
document.getElementsByClassName("mech-mod-2-18")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/wDFsAaLzx0E")
})
document.getElementsByClassName("mech-mod-2-19")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/PQ4E79zvdno")
})


// mechsics module 3 -----------------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-3-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/bHNtm7Gk3vE")
})
document.getElementsByClassName("mech-mod-3-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/hKOBxI5bkwI")
})
document.getElementsByClassName("mech-mod-3-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/Vuzz9ZOMSO4")
})
document.getElementsByClassName("mech-mod-3-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/AMyvtA6c3lI")
})
document.getElementsByClassName("mech-mod-3-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/T3-9D2M12hs")
})
document.getElementsByClassName("mech-mod-3-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/RsrH6jRlLx8")
})
document.getElementsByClassName("mech-mod-3-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/Ure9GQ1LXW8")
})
document.getElementsByClassName("mech-mod-3-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/Ure9GQ1LXW8")
})
document.getElementsByClassName("mech-mod-3-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/SRZkclYh9eY")
})
document.getElementsByClassName("mech-mod-3-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/j-rHqTfDmUI")
})
document.getElementsByClassName("mech-mod-3-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/bofwin3EfJA")
})
document.getElementsByClassName("mech-mod-3-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/TGVOJIBczK8")
})
document.getElementsByClassName("mech-mod-3-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/sy2mvyY-0uo")
})
document.getElementsByClassName("mech-mod-3-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/q6UlVhI435M")
})
document.getElementsByClassName("mech-mod-3-15")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/vj3-_5JfP1E")
})
document.getElementsByClassName("mech-mod-3-16")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/yQeqo8u9oe8")
})
document.getElementsByClassName("mech-mod-3-17")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/cghBs6K_YsM")
})
document.getElementsByClassName("mech-mod-3-18")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/DzcFs__C9wU")
})
document.getElementsByClassName("mech-mod-3-19")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/MuLBP6xic_g")
})
document.getElementsByClassName("mech-mod-3-20")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/s1bogpSvaSU")
})
document.getElementsByClassName("mech-mod-3-21")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/tVO3LxkM_rw")
})
document.getElementsByClassName("mech-mod-3-22")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/9m2Iodm7f7k")
})

// mechsics module 4-------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-4-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/wKUFMQ012yk")
})
document.getElementsByClassName("mech-mod-4-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/3PEuO1uJZzM")
})
document.getElementsByClassName("mech-mod-4-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/5m6gE7pd7nY")
})
document.getElementsByClassName("mech-mod-4-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/X0oGPtfuwxs")
})
document.getElementsByClassName("mech-mod-4-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/SxrDI5oLJ4s")
})
document.getElementsByClassName("mech-mod-4-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/1EbYUPwSxL4")
})
document.getElementsByClassName("mech-mod-4-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/LFgp8al-J8I")
})
document.getElementsByClassName("mech-mod-4-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/1wfs7rwLWnU")
})
document.getElementsByClassName("mech-mod-4-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/5BxKGRuH730")
})
document.getElementsByClassName("mech-mod-4-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/MiyZI6PNL0c")
})
document.getElementsByClassName("mech-mod-4-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/QqpBpxXna6w")
})
document.getElementsByClassName("mech-mod-4-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/9AWKkTPqrJE")
})
document.getElementsByClassName("mech-mod-4-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/_SXsf03lluE")
})
document.getElementsByClassName("mech-mod-4-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/TSXS4FqzxAQ")
})
document.getElementsByClassName("mech-mod-4-15")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/rLpQMV2QBuQ")
})
document.getElementsByClassName("mech-mod-4-16")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/QEMztaSUAfA")
})
document.getElementsByClassName("mech-mod-4-17")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/lqv9f5qPzxU")
})
document.getElementsByClassName("mech-mod-4-18")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/DE0hWLdkckg")
})
document.getElementsByClassName("mech-mod-4-19")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","https://www.youtube.com/embed/8m0VP5_feOY")
})


// module 5 mechsics---------------------------------------------------------------------------------------------------------------------------

document.getElementsByClassName("mech-mod-5-1")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-2")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-3")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-4")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-5")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-6")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-7")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-8")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-9")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-10")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-10.0")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-11")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-12")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-13")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})
document.getElementsByClassName("mech-mod-5-14")[0].addEventListener("click",function(){
    document.getElementsByClassName("mech-vid")[0].setAttribute("src","")
})


